#include "keys.h"

// '#macro' will return the name of the macro as str
#define MACRO_NAME(macro) [macro] = #macro

/**
 *  If a macro is not implemented on your kernal version wrap with define macro:
 *      #if define KEY_
 *          MACRO_NAME(KEY_)
 *      #endif
 *   
 *  Note: The following have multiple mappings only one is listed...
 *       KEY_HANGUEL		KEY_HANGEUL
 *       KEY_SCREENLOCK		KEY_COFFEE
 *       KEY_DIRECTION		KEY_ROTATE_DISPLAY
 *       KEY_BRIGHTNESS_ZERO		KEY_BRIGHTNESS_AUTO
 *       KEY_WIMAX		KEY_WWAN
 *       BTN_A		BTN_SOUTH
 *       BTN_B		BTN_EAST
 *       BTN_X		BTN_NORTH
 *       BTN_Y		BTN_WEST
 *       KEY_ZOOM		KEY_FULL_SCREEN
 *       KEY_SCREEN		KEY_ASPECT_RATIO
 *       KEY_BRIGHTNESS_TOGGLE		KEY_DISPLAY*TOGGLE
 */
static const char *const key_macro_names[KEY_CNT] = {
    [0 ... KEY_MAX] = NULL,
    MACRO_NAME(KEY_RESERVED),
    MACRO_NAME(KEY_ESC),
    MACRO_NAME(KEY_1),
    MACRO_NAME(KEY_2),
    MACRO_NAME(KEY_3),
    MACRO_NAME(KEY_4),
    MACRO_NAME(KEY_5),
    MACRO_NAME(KEY_6),
    MACRO_NAME(KEY_7),
    MACRO_NAME(KEY_8),
    MACRO_NAME(KEY_9),
    MACRO_NAME(KEY_0),
    MACRO_NAME(KEY_MINUS),
    MACRO_NAME(KEY_EQUAL),
    MACRO_NAME(KEY_BACKSPACE),
    MACRO_NAME(KEY_TAB),
    MACRO_NAME(KEY_Q),
    MACRO_NAME(KEY_W),
    MACRO_NAME(KEY_E),
    MACRO_NAME(KEY_R),
    MACRO_NAME(KEY_T),
    MACRO_NAME(KEY_Y),
    MACRO_NAME(KEY_U),
    MACRO_NAME(KEY_I),
    MACRO_NAME(KEY_O),
    MACRO_NAME(KEY_P),
    MACRO_NAME(KEY_LEFTBRACE),
    MACRO_NAME(KEY_RIGHTBRACE),
    MACRO_NAME(KEY_ENTER),
    MACRO_NAME(KEY_LEFTCTRL),
    MACRO_NAME(KEY_A),
    MACRO_NAME(KEY_S),
    MACRO_NAME(KEY_D),
    MACRO_NAME(KEY_F),
    MACRO_NAME(KEY_G),
    MACRO_NAME(KEY_H),
    MACRO_NAME(KEY_J),
    MACRO_NAME(KEY_K),
    MACRO_NAME(KEY_L),
    MACRO_NAME(KEY_SEMICOLON),
    MACRO_NAME(KEY_APOSTROPHE),
    MACRO_NAME(KEY_GRAVE),
    MACRO_NAME(KEY_LEFTSHIFT),
    MACRO_NAME(KEY_BACKSLASH),
    MACRO_NAME(KEY_Z),
    MACRO_NAME(KEY_X),
    MACRO_NAME(KEY_C),
    MACRO_NAME(KEY_V),
    MACRO_NAME(KEY_B),
    MACRO_NAME(KEY_N),
    MACRO_NAME(KEY_M),
    MACRO_NAME(KEY_COMMA),
    MACRO_NAME(KEY_DOT),
    MACRO_NAME(KEY_SLASH),
    MACRO_NAME(KEY_RIGHTSHIFT),
    MACRO_NAME(KEY_KPASTERISK),
    MACRO_NAME(KEY_LEFTALT),
    MACRO_NAME(KEY_SPACE),
    MACRO_NAME(KEY_CAPSLOCK),
    MACRO_NAME(KEY_F1),
    MACRO_NAME(KEY_F2),
    MACRO_NAME(KEY_F3),
    MACRO_NAME(KEY_F4),
    MACRO_NAME(KEY_F5),
    MACRO_NAME(KEY_F6),
    MACRO_NAME(KEY_F7),
    MACRO_NAME(KEY_F8),
    MACRO_NAME(KEY_F9),
    MACRO_NAME(KEY_F10),
    MACRO_NAME(KEY_NUMLOCK),
    MACRO_NAME(KEY_SCROLLLOCK),
    MACRO_NAME(KEY_KP7),
    MACRO_NAME(KEY_KP8),
    MACRO_NAME(KEY_KP9),
    MACRO_NAME(KEY_KPMINUS),
    MACRO_NAME(KEY_KP4),
    MACRO_NAME(KEY_KP5),
    MACRO_NAME(KEY_KP6),
    MACRO_NAME(KEY_KPPLUS),
    MACRO_NAME(KEY_KP1),
    MACRO_NAME(KEY_KP2),
    MACRO_NAME(KEY_KP3),
    MACRO_NAME(KEY_KP0),
    MACRO_NAME(KEY_KPDOT),
    MACRO_NAME(KEY_ZENKAKUHANKAKU),
    MACRO_NAME(KEY_102ND),
    MACRO_NAME(KEY_F11),
    MACRO_NAME(KEY_F12),
    MACRO_NAME(KEY_RO),
    MACRO_NAME(KEY_KATAKANA),
    MACRO_NAME(KEY_HIRAGANA),
    MACRO_NAME(KEY_HENKAN),
    MACRO_NAME(KEY_KATAKANAHIRAGANA),
    MACRO_NAME(KEY_MUHENKAN),
    MACRO_NAME(KEY_KPJPCOMMA),
    MACRO_NAME(KEY_KPENTER),
    MACRO_NAME(KEY_RIGHTCTRL),
    MACRO_NAME(KEY_KPSLASH),
    MACRO_NAME(KEY_SYSRQ),
    MACRO_NAME(KEY_RIGHTALT),
    MACRO_NAME(KEY_LINEFEED),
    MACRO_NAME(KEY_HOME),
    MACRO_NAME(KEY_UP),
    MACRO_NAME(KEY_PAGEUP),
    MACRO_NAME(KEY_LEFT),
    MACRO_NAME(KEY_RIGHT),
    MACRO_NAME(KEY_END),
    MACRO_NAME(KEY_DOWN),
    MACRO_NAME(KEY_PAGEDOWN),
    MACRO_NAME(KEY_INSERT),
    MACRO_NAME(KEY_DELETE),
    MACRO_NAME(KEY_MACRO),
    MACRO_NAME(KEY_MUTE),
    MACRO_NAME(KEY_VOLUMEDOWN),
    MACRO_NAME(KEY_VOLUMEUP),
    MACRO_NAME(KEY_POWER),
    MACRO_NAME(KEY_KPEQUAL),
    MACRO_NAME(KEY_KPPLUSMINUS),
    MACRO_NAME(KEY_PAUSE),
    MACRO_NAME(KEY_SCALE),
    MACRO_NAME(KEY_KPCOMMA),
    MACRO_NAME(KEY_HANGEUL),
    MACRO_NAME(KEY_HANJA),
    MACRO_NAME(KEY_YEN),
    MACRO_NAME(KEY_LEFTMETA),
    MACRO_NAME(KEY_RIGHTMETA),
    MACRO_NAME(KEY_COMPOSE),
    MACRO_NAME(KEY_STOP),
    MACRO_NAME(KEY_AGAIN),
    MACRO_NAME(KEY_PROPS),
    MACRO_NAME(KEY_UNDO),
    MACRO_NAME(KEY_FRONT),
    MACRO_NAME(KEY_COPY),
    MACRO_NAME(KEY_OPEN),
    MACRO_NAME(KEY_PASTE),
    MACRO_NAME(KEY_FIND),
    MACRO_NAME(KEY_CUT),
    MACRO_NAME(KEY_HELP),
    MACRO_NAME(KEY_MENU),
    MACRO_NAME(KEY_CALC),
    MACRO_NAME(KEY_SETUP),
    MACRO_NAME(KEY_SLEEP),
    MACRO_NAME(KEY_WAKEUP),
    MACRO_NAME(KEY_FILE),
    MACRO_NAME(KEY_SENDFILE),
    MACRO_NAME(KEY_DELETEFILE),
    MACRO_NAME(KEY_XFER),
    MACRO_NAME(KEY_PROG1),
    MACRO_NAME(KEY_PROG2),
    MACRO_NAME(KEY_WWW),
    MACRO_NAME(KEY_MSDOS),
    MACRO_NAME(KEY_COFFEE),
    MACRO_NAME(KEY_ROTATE_DISPLAY),
    MACRO_NAME(KEY_CYCLEWINDOWS),
    MACRO_NAME(KEY_MAIL),
    MACRO_NAME(KEY_BOOKMARKS),
    MACRO_NAME(KEY_COMPUTER),
    MACRO_NAME(KEY_BACK),
    MACRO_NAME(KEY_FORWARD),
    MACRO_NAME(KEY_CLOSECD),
    MACRO_NAME(KEY_EJECTCD),
    MACRO_NAME(KEY_EJECTCLOSECD),
    MACRO_NAME(KEY_NEXTSONG),
    MACRO_NAME(KEY_PLAYPAUSE),
    MACRO_NAME(KEY_PREVIOUSSONG),
    MACRO_NAME(KEY_STOPCD),
    MACRO_NAME(KEY_RECORD),
    MACRO_NAME(KEY_REWIND),
    MACRO_NAME(KEY_PHONE),
    MACRO_NAME(KEY_ISO),
    MACRO_NAME(KEY_CONFIG),
    MACRO_NAME(KEY_HOMEPAGE),
    MACRO_NAME(KEY_REFRESH),
    MACRO_NAME(KEY_EXIT),
    MACRO_NAME(KEY_MOVE),
    MACRO_NAME(KEY_EDIT),
    MACRO_NAME(KEY_SCROLLUP),
    MACRO_NAME(KEY_SCROLLDOWN),
    MACRO_NAME(KEY_KPLEFTPAREN),
    MACRO_NAME(KEY_KPRIGHTPAREN),
    MACRO_NAME(KEY_NEW),
    MACRO_NAME(KEY_REDO),
    MACRO_NAME(KEY_F13),
    MACRO_NAME(KEY_F14),
    MACRO_NAME(KEY_F15),
    MACRO_NAME(KEY_F16),
    MACRO_NAME(KEY_F17),
    MACRO_NAME(KEY_F18),
    MACRO_NAME(KEY_F19),
    MACRO_NAME(KEY_F20),
    MACRO_NAME(KEY_F21),
    MACRO_NAME(KEY_F22),
    MACRO_NAME(KEY_F23),
    MACRO_NAME(KEY_F24),
    MACRO_NAME(KEY_PLAYCD),
    MACRO_NAME(KEY_PAUSECD),
    MACRO_NAME(KEY_PROG3),
    MACRO_NAME(KEY_PROG4),
    MACRO_NAME(KEY_DASHBOARD),
    MACRO_NAME(KEY_SUSPEND),
    MACRO_NAME(KEY_CLOSE),
    MACRO_NAME(KEY_PLAY),
    MACRO_NAME(KEY_FASTFORWARD),
    MACRO_NAME(KEY_BASSBOOST),
    MACRO_NAME(KEY_PRINT),
    MACRO_NAME(KEY_HP),
    MACRO_NAME(KEY_CAMERA),
    MACRO_NAME(KEY_SOUND),
    MACRO_NAME(KEY_QUESTION),
    MACRO_NAME(KEY_EMAIL),
    MACRO_NAME(KEY_CHAT),
    MACRO_NAME(KEY_SEARCH),
    MACRO_NAME(KEY_CONNECT),
    MACRO_NAME(KEY_FINANCE),
    MACRO_NAME(KEY_SPORT),
    MACRO_NAME(KEY_SHOP),
    MACRO_NAME(KEY_ALTERASE),
    MACRO_NAME(KEY_CANCEL),
    MACRO_NAME(KEY_BRIGHTNESSDOWN),
    MACRO_NAME(KEY_BRIGHTNESSUP),
    MACRO_NAME(KEY_MEDIA),
    MACRO_NAME(KEY_SWITCHVIDEOMODE),
    MACRO_NAME(KEY_KBDILLUMTOGGLE),
    MACRO_NAME(KEY_KBDILLUMDOWN),
    MACRO_NAME(KEY_KBDILLUMUP),
    MACRO_NAME(KEY_SEND),
    MACRO_NAME(KEY_REPLY),
    MACRO_NAME(KEY_FORWARDMAIL),
    MACRO_NAME(KEY_SAVE),
    MACRO_NAME(KEY_DOCUMENTS),
    MACRO_NAME(KEY_BATTERY),
    MACRO_NAME(KEY_BLUETOOTH),
    MACRO_NAME(KEY_WLAN),
    MACRO_NAME(KEY_UWB),
    MACRO_NAME(KEY_UNKNOWN),
    MACRO_NAME(KEY_VIDEO_NEXT),
    MACRO_NAME(KEY_VIDEO_PREV),
    MACRO_NAME(KEY_BRIGHTNESS_CYCLE),
    MACRO_NAME(KEY_BRIGHTNESS_AUTO),
    MACRO_NAME(KEY_DISPLAY_OFF),
    MACRO_NAME(KEY_WWAN),
    MACRO_NAME(KEY_RFKILL),
    MACRO_NAME(KEY_MICMUTE),
    MACRO_NAME(BTN_MISC),
    MACRO_NAME(BTN_0),
    MACRO_NAME(BTN_1),
    MACRO_NAME(BTN_2),
    MACRO_NAME(BTN_3),
    MACRO_NAME(BTN_4),
    MACRO_NAME(BTN_5),
    MACRO_NAME(BTN_6),
    MACRO_NAME(BTN_7),
    MACRO_NAME(BTN_8),
    MACRO_NAME(BTN_9),
    MACRO_NAME(BTN_MOUSE),
    MACRO_NAME(BTN_LEFT),
    MACRO_NAME(BTN_RIGHT),
    MACRO_NAME(BTN_MIDDLE),
    MACRO_NAME(BTN_SIDE),
    MACRO_NAME(BTN_EXTRA),
    MACRO_NAME(BTN_FORWARD),
    MACRO_NAME(BTN_BACK),
    MACRO_NAME(BTN_TASK),
    MACRO_NAME(BTN_JOYSTICK),
    MACRO_NAME(BTN_TRIGGER),
    MACRO_NAME(BTN_THUMB),
    MACRO_NAME(BTN_THUMB2),
    MACRO_NAME(BTN_TOP),
    MACRO_NAME(BTN_TOP2),
    MACRO_NAME(BTN_PINKIE),
    MACRO_NAME(BTN_BASE),
    MACRO_NAME(BTN_BASE2),
    MACRO_NAME(BTN_BASE3),
    MACRO_NAME(BTN_BASE4),
    MACRO_NAME(BTN_BASE5),
    MACRO_NAME(BTN_BASE6),
    MACRO_NAME(BTN_DEAD),
    MACRO_NAME(BTN_GAMEPAD),
    MACRO_NAME(BTN_SOUTH),
    MACRO_NAME(BTN_EAST),
    MACRO_NAME(BTN_C),
    MACRO_NAME(BTN_NORTH),
    MACRO_NAME(BTN_WEST),
    MACRO_NAME(BTN_Z),
    MACRO_NAME(BTN_TL),
    MACRO_NAME(BTN_TR),
    MACRO_NAME(BTN_TL2),
    MACRO_NAME(BTN_TR2),
    MACRO_NAME(BTN_SELECT),
    MACRO_NAME(BTN_START),
    MACRO_NAME(BTN_MODE),
    MACRO_NAME(BTN_THUMBL),
    MACRO_NAME(BTN_THUMBR),
    MACRO_NAME(BTN_DIGI),
    MACRO_NAME(BTN_TOOL_PEN),
    MACRO_NAME(BTN_TOOL_RUBBER),
    MACRO_NAME(BTN_TOOL_BRUSH),
    MACRO_NAME(BTN_TOOL_PENCIL),
    MACRO_NAME(BTN_TOOL_AIRBRUSH),
    MACRO_NAME(BTN_TOOL_FINGER),
    MACRO_NAME(BTN_TOOL_MOUSE),
    MACRO_NAME(BTN_TOOL_LENS),
    MACRO_NAME(BTN_TOOL_QUINTTAP),
    MACRO_NAME(BTN_STYLUS3),
    MACRO_NAME(BTN_TOUCH),
    MACRO_NAME(BTN_STYLUS),
    MACRO_NAME(BTN_STYLUS2),
    MACRO_NAME(BTN_TOOL_DOUBLETAP),
    MACRO_NAME(BTN_TOOL_TRIPLETAP),
    MACRO_NAME(BTN_TOOL_QUADTAP),
    MACRO_NAME(BTN_WHEEL),
    MACRO_NAME(BTN_GEAR_DOWN),
    MACRO_NAME(BTN_GEAR_UP),
    MACRO_NAME(KEY_OK),
    MACRO_NAME(KEY_SELECT),
    MACRO_NAME(KEY_GOTO),
    MACRO_NAME(KEY_CLEAR),
    MACRO_NAME(KEY_POWER2),
    MACRO_NAME(KEY_OPTION),
    MACRO_NAME(KEY_INFO),
    MACRO_NAME(KEY_TIME),
    MACRO_NAME(KEY_VENDOR),
    MACRO_NAME(KEY_ARCHIVE),
    MACRO_NAME(KEY_PROGRAM),
    MACRO_NAME(KEY_CHANNEL),
    MACRO_NAME(KEY_FAVORITES),
    MACRO_NAME(KEY_EPG),
    MACRO_NAME(KEY_PVR),
    MACRO_NAME(KEY_MHP),
    MACRO_NAME(KEY_LANGUAGE),
    MACRO_NAME(KEY_TITLE),
    MACRO_NAME(KEY_SUBTITLE),
    MACRO_NAME(KEY_ANGLE),
    MACRO_NAME(KEY_FULL_SCREEN),
    MACRO_NAME(KEY_MODE),
    MACRO_NAME(KEY_KEYBOARD),
    MACRO_NAME(KEY_ASPECT_RATIO),
    MACRO_NAME(KEY_PC),
    MACRO_NAME(KEY_TV),
    MACRO_NAME(KEY_TV2),
    MACRO_NAME(KEY_VCR),
    MACRO_NAME(KEY_VCR2),
    MACRO_NAME(KEY_SAT),
    MACRO_NAME(KEY_SAT2),
    MACRO_NAME(KEY_CD),
    MACRO_NAME(KEY_TAPE),
    MACRO_NAME(KEY_RADIO),
    MACRO_NAME(KEY_TUNER),
    MACRO_NAME(KEY_PLAYER),
    MACRO_NAME(KEY_TEXT),
    MACRO_NAME(KEY_DVD),
    MACRO_NAME(KEY_AUX),
    MACRO_NAME(KEY_MP3),
    MACRO_NAME(KEY_AUDIO),
    MACRO_NAME(KEY_VIDEO),
    MACRO_NAME(KEY_DIRECTORY),
    MACRO_NAME(KEY_LIST),
    MACRO_NAME(KEY_MEMO),
    MACRO_NAME(KEY_CALENDAR),
    MACRO_NAME(KEY_RED),
    MACRO_NAME(KEY_GREEN),
    MACRO_NAME(KEY_YELLOW),
    MACRO_NAME(KEY_BLUE),
    MACRO_NAME(KEY_CHANNELUP),
    MACRO_NAME(KEY_CHANNELDOWN),
    MACRO_NAME(KEY_FIRST),
    MACRO_NAME(KEY_LAST),
    MACRO_NAME(KEY_AB),
    MACRO_NAME(KEY_NEXT),
    MACRO_NAME(KEY_RESTART),
    MACRO_NAME(KEY_SLOW),
    MACRO_NAME(KEY_SHUFFLE),
    MACRO_NAME(KEY_BREAK),
    MACRO_NAME(KEY_PREVIOUS),
    MACRO_NAME(KEY_DIGITS),
    MACRO_NAME(KEY_TEEN),
    MACRO_NAME(KEY_TWEN),
    MACRO_NAME(KEY_VIDEOPHONE),
    MACRO_NAME(KEY_GAMES),
    MACRO_NAME(KEY_ZOOMIN),
    MACRO_NAME(KEY_ZOOMOUT),
    MACRO_NAME(KEY_ZOOMRESET),
    MACRO_NAME(KEY_WORDPROCESSOR),
    MACRO_NAME(KEY_EDITOR),
    MACRO_NAME(KEY_SPREADSHEET),
    MACRO_NAME(KEY_GRAPHICSEDITOR),
    MACRO_NAME(KEY_PRESENTATION),
    MACRO_NAME(KEY_DATABASE),
    MACRO_NAME(KEY_NEWS),
    MACRO_NAME(KEY_VOICEMAIL),
    MACRO_NAME(KEY_ADDRESSBOOK),
    MACRO_NAME(KEY_MESSENGER),
    MACRO_NAME(KEY_DISPLAYTOGGLE),
    MACRO_NAME(KEY_SPELLCHECK),
    MACRO_NAME(KEY_LOGOFF),
    MACRO_NAME(KEY_DOLLAR),
    MACRO_NAME(KEY_EURO),
    MACRO_NAME(KEY_FRAMEBACK),
    MACRO_NAME(KEY_FRAMEFORWARD),
    MACRO_NAME(KEY_CONTEXT_MENU),
    MACRO_NAME(KEY_MEDIA_REPEAT),
    MACRO_NAME(KEY_10CHANNELSUP),
    MACRO_NAME(KEY_10CHANNELSDOWN),
    MACRO_NAME(KEY_IMAGES),
    MACRO_NAME(KEY_DEL_EOL),
    MACRO_NAME(KEY_DEL_EOS),
    MACRO_NAME(KEY_INS_LINE),
    MACRO_NAME(KEY_DEL_LINE),
    MACRO_NAME(KEY_FN),
    MACRO_NAME(KEY_FN_ESC),
    MACRO_NAME(KEY_FN_F1),
    MACRO_NAME(KEY_FN_F2),
    MACRO_NAME(KEY_FN_F3),
    MACRO_NAME(KEY_FN_F4),
    MACRO_NAME(KEY_FN_F5),
    MACRO_NAME(KEY_FN_F6),
    MACRO_NAME(KEY_FN_F7),
    MACRO_NAME(KEY_FN_F8),
    MACRO_NAME(KEY_FN_F9),
    MACRO_NAME(KEY_FN_F10),
    MACRO_NAME(KEY_FN_F11),
    MACRO_NAME(KEY_FN_F12),
    MACRO_NAME(KEY_FN_1),
    MACRO_NAME(KEY_FN_2),
    MACRO_NAME(KEY_FN_D),
    MACRO_NAME(KEY_FN_E),
    MACRO_NAME(KEY_FN_F),
    MACRO_NAME(KEY_FN_S),
    MACRO_NAME(KEY_FN_B),
    MACRO_NAME(KEY_BRL_DOT1),
    MACRO_NAME(KEY_BRL_DOT2),
    MACRO_NAME(KEY_BRL_DOT3),
    MACRO_NAME(KEY_BRL_DOT4),
    MACRO_NAME(KEY_BRL_DOT5),
    MACRO_NAME(KEY_BRL_DOT6),
    MACRO_NAME(KEY_BRL_DOT7),
    MACRO_NAME(KEY_BRL_DOT8),
    MACRO_NAME(KEY_BRL_DOT9),
    MACRO_NAME(KEY_BRL_DOT10),
    MACRO_NAME(KEY_NUMERIC_0),
    MACRO_NAME(KEY_NUMERIC_1),
    MACRO_NAME(KEY_NUMERIC_2),
    MACRO_NAME(KEY_NUMERIC_3),
    MACRO_NAME(KEY_NUMERIC_4),
    MACRO_NAME(KEY_NUMERIC_5),
    MACRO_NAME(KEY_NUMERIC_6),
    MACRO_NAME(KEY_NUMERIC_7),
    MACRO_NAME(KEY_NUMERIC_8),
    MACRO_NAME(KEY_NUMERIC_9),
    MACRO_NAME(KEY_NUMERIC_STAR),
    MACRO_NAME(KEY_NUMERIC_POUND),
    MACRO_NAME(KEY_NUMERIC_A),
    MACRO_NAME(KEY_NUMERIC_B),
    MACRO_NAME(KEY_NUMERIC_C),
    MACRO_NAME(KEY_NUMERIC_D),
    MACRO_NAME(KEY_CAMERA_FOCUS),
    MACRO_NAME(KEY_WPS_BUTTON),
    MACRO_NAME(KEY_TOUCHPAD_TOGGLE),
    MACRO_NAME(KEY_TOUCHPAD_ON),
    MACRO_NAME(KEY_TOUCHPAD_OFF),
    MACRO_NAME(KEY_CAMERA_ZOOMIN),
    MACRO_NAME(KEY_CAMERA_ZOOMOUT),
    MACRO_NAME(KEY_CAMERA_UP),
    MACRO_NAME(KEY_CAMERA_DOWN),
    MACRO_NAME(KEY_CAMERA_LEFT),
    MACRO_NAME(KEY_CAMERA_RIGHT),
    MACRO_NAME(KEY_ATTENDANT_ON),
    MACRO_NAME(KEY_ATTENDANT_OFF),
    MACRO_NAME(KEY_ATTENDANT_TOGGLE),
    MACRO_NAME(KEY_LIGHTS_TOGGLE),
    MACRO_NAME(BTN_DPAD_UP),
    MACRO_NAME(BTN_DPAD_DOWN),
    MACRO_NAME(BTN_DPAD_LEFT),
    MACRO_NAME(BTN_DPAD_RIGHT),
    MACRO_NAME(KEY_ALS_TOGGLE),
    MACRO_NAME(KEY_ROTATE_LOCK_TOGGLE),
    MACRO_NAME(KEY_BUTTONCONFIG),
    MACRO_NAME(KEY_TASKMANAGER),
    MACRO_NAME(KEY_JOURNAL),
    MACRO_NAME(KEY_CONTROLPANEL),
    MACRO_NAME(KEY_APPSELECT),
    MACRO_NAME(KEY_SCREENSAVER),
    MACRO_NAME(KEY_VOICECOMMAND),
    MACRO_NAME(KEY_ASSISTANT),
    MACRO_NAME(KEY_KBD_LAYOUT_NEXT),
    MACRO_NAME(KEY_BRIGHTNESS_MIN),
    MACRO_NAME(KEY_BRIGHTNESS_MAX),
    MACRO_NAME(KEY_KBDINPUTASSIST_PREV),
    MACRO_NAME(KEY_KBDINPUTASSIST_NEXT),
    MACRO_NAME(KEY_KBDINPUTASSIST_PREVGROUP),
    MACRO_NAME(KEY_KBDINPUTASSIST_NEXTGROUP),
    MACRO_NAME(KEY_KBDINPUTASSIST_ACCEPT),
    MACRO_NAME(KEY_KBDINPUTASSIST_CANCEL),
    MACRO_NAME(KEY_RIGHT_UP),
    MACRO_NAME(KEY_RIGHT_DOWN),
    MACRO_NAME(KEY_LEFT_UP),
    MACRO_NAME(KEY_LEFT_DOWN),
    MACRO_NAME(KEY_ROOT_MENU),
    MACRO_NAME(KEY_MEDIA_TOP_MENU),
    MACRO_NAME(KEY_NUMERIC_11),
    MACRO_NAME(KEY_NUMERIC_12),
    MACRO_NAME(KEY_AUDIO_DESC),
    MACRO_NAME(KEY_3D_MODE),
    MACRO_NAME(KEY_NEXT_FAVORITE),
    MACRO_NAME(KEY_STOP_RECORD),
    MACRO_NAME(KEY_PAUSE_RECORD),
    MACRO_NAME(KEY_VOD),
    MACRO_NAME(KEY_UNMUTE),
    MACRO_NAME(KEY_FASTREVERSE),
    MACRO_NAME(KEY_SLOWREVERSE),
    MACRO_NAME(KEY_DATA),
    MACRO_NAME(KEY_ONSCREEN_KEYBOARD),
    MACRO_NAME(KEY_PRIVACY_SCREEN_TOGGLE),
    MACRO_NAME(KEY_SELECTIVE_SCREENSHOT),
    MACRO_NAME(KEY_MACRO1),
    MACRO_NAME(KEY_MACRO2),
    MACRO_NAME(KEY_MACRO3),
    MACRO_NAME(KEY_MACRO4),
    MACRO_NAME(KEY_MACRO5),
    MACRO_NAME(KEY_MACRO6),
    MACRO_NAME(KEY_MACRO7),
    MACRO_NAME(KEY_MACRO8),
    MACRO_NAME(KEY_MACRO9),
    MACRO_NAME(KEY_MACRO10),
    MACRO_NAME(KEY_MACRO11),
    MACRO_NAME(KEY_MACRO12),
    MACRO_NAME(KEY_MACRO13),
    MACRO_NAME(KEY_MACRO14),
    MACRO_NAME(KEY_MACRO15),
    MACRO_NAME(KEY_MACRO16),
    MACRO_NAME(KEY_MACRO17),
    MACRO_NAME(KEY_MACRO18),
    MACRO_NAME(KEY_MACRO19),
    MACRO_NAME(KEY_MACRO20),
    MACRO_NAME(KEY_MACRO21),
    MACRO_NAME(KEY_MACRO22),
    MACRO_NAME(KEY_MACRO23),
    MACRO_NAME(KEY_MACRO24),
    MACRO_NAME(KEY_MACRO25),
    MACRO_NAME(KEY_MACRO26),
    MACRO_NAME(KEY_MACRO27),
    MACRO_NAME(KEY_MACRO28),
    MACRO_NAME(KEY_MACRO29),
    MACRO_NAME(KEY_MACRO30),
    MACRO_NAME(KEY_MACRO_RECORD_START),
    MACRO_NAME(KEY_MACRO_RECORD_STOP),
    MACRO_NAME(KEY_MACRO_PRESET_CYCLE),
    MACRO_NAME(KEY_MACRO_PRESET1),
    MACRO_NAME(KEY_MACRO_PRESET2),
    MACRO_NAME(KEY_MACRO_PRESET3),
    MACRO_NAME(KEY_KBD_LCD_MENU1),
    MACRO_NAME(KEY_KBD_LCD_MENU2),
    MACRO_NAME(KEY_KBD_LCD_MENU3),
    MACRO_NAME(KEY_KBD_LCD_MENU4),
    MACRO_NAME(KEY_KBD_LCD_MENU5),
    MACRO_NAME(BTN_TRIGGER_HAPPY),
    MACRO_NAME(BTN_TRIGGER_HAPPY1),
    MACRO_NAME(BTN_TRIGGER_HAPPY2),
    MACRO_NAME(BTN_TRIGGER_HAPPY3),
    MACRO_NAME(BTN_TRIGGER_HAPPY4),
    MACRO_NAME(BTN_TRIGGER_HAPPY5),
    MACRO_NAME(BTN_TRIGGER_HAPPY6),
    MACRO_NAME(BTN_TRIGGER_HAPPY7),
    MACRO_NAME(BTN_TRIGGER_HAPPY8),
    MACRO_NAME(BTN_TRIGGER_HAPPY9),
    MACRO_NAME(BTN_TRIGGER_HAPPY10),
    MACRO_NAME(BTN_TRIGGER_HAPPY11),
    MACRO_NAME(BTN_TRIGGER_HAPPY12),
    MACRO_NAME(BTN_TRIGGER_HAPPY13),
    MACRO_NAME(BTN_TRIGGER_HAPPY14),
    MACRO_NAME(BTN_TRIGGER_HAPPY15),
    MACRO_NAME(BTN_TRIGGER_HAPPY16),
    MACRO_NAME(BTN_TRIGGER_HAPPY17),
    MACRO_NAME(BTN_TRIGGER_HAPPY18),
    MACRO_NAME(BTN_TRIGGER_HAPPY19),
    MACRO_NAME(BTN_TRIGGER_HAPPY20),
    MACRO_NAME(BTN_TRIGGER_HAPPY21),
    MACRO_NAME(BTN_TRIGGER_HAPPY22),
    MACRO_NAME(BTN_TRIGGER_HAPPY23),
    MACRO_NAME(BTN_TRIGGER_HAPPY24),
    MACRO_NAME(BTN_TRIGGER_HAPPY25),
    MACRO_NAME(BTN_TRIGGER_HAPPY26),
    MACRO_NAME(BTN_TRIGGER_HAPPY27),
    MACRO_NAME(BTN_TRIGGER_HAPPY28),
    MACRO_NAME(BTN_TRIGGER_HAPPY29),
    MACRO_NAME(BTN_TRIGGER_HAPPY30),
    MACRO_NAME(BTN_TRIGGER_HAPPY31),
    MACRO_NAME(BTN_TRIGGER_HAPPY32),
    MACRO_NAME(BTN_TRIGGER_HAPPY33),
    MACRO_NAME(BTN_TRIGGER_HAPPY34),
    MACRO_NAME(BTN_TRIGGER_HAPPY35),
    MACRO_NAME(BTN_TRIGGER_HAPPY36),
    MACRO_NAME(BTN_TRIGGER_HAPPY37),
    MACRO_NAME(BTN_TRIGGER_HAPPY38),
    MACRO_NAME(BTN_TRIGGER_HAPPY39),
    MACRO_NAME(BTN_TRIGGER_HAPPY40)};

const char* key_name(const unsigned int key_code){
    if(key_code < KEY_CNT) 
        return key_macro_names[key_code];
    return NULL;
}

int key_code(const char* key){
    size_t index = 0;

    for (; index < KEY_CNT; index++ ){
        if (key_macro_names[index] == NULL) continue;
        if (STRING_EQUALS(key,key_macro_names[index])) 
            return index;
    }
    // Fix for duplicate keys
    if(STRING_EQUALS(key,"KEY_HANGUEL")) return KEY_HANGUEL;
    if(STRING_EQUALS(key,"KEY_SCREENLOCK")) return KEY_SCREENLOCK;
    if(STRING_EQUALS(key,"KEY_DIRECTION")) return KEY_DIRECTION;
    if(STRING_EQUALS(key,"KEY_BRIGHTNESS_ZERO")) return KEY_BRIGHTNESS_ZERO;
    if(STRING_EQUALS(key,"KEY_WIMAX")) return KEY_WIMAX;
    if(STRING_EQUALS(key,"BTN_A")) return BTN_A;
    if(STRING_EQUALS(key,"BTN_B")) return BTN_B;
    if(STRING_EQUALS(key,"BTN_X")) return BTN_X;
    if(STRING_EQUALS(key,"BTN_Y")) return BTN_Y;
    if(STRING_EQUALS(key,"KEY_ZOOM")) return KEY_ZOOM;
    if(STRING_EQUALS(key,"KEY_SCREEN")) return KEY_SCREEN;
    if(STRING_EQUALS(key,"KEY_BRIGHTNESS_TOGGLE")) return KEY_BRIGHTNESS_TOGGLE;

    return -1;
}

bool enabled_code(unsigned int bit, unsigned long *array)
{
    // size of long can change based on complier settings
    // 8 bits per 1 byte. sizeof(long) unit is bytes
    unsigned long long_bits = sizeof(long) * 8;
    // index where the bit we are checking is stored
    unsigned long index = bit / long_bits;
    // get the offset to shift the frame
    unsigned long offset = bit % long_bits;
    // check the last digit is 1 in base 2
    return ((array[index] >> offset) & 1);
}

int get_valid_keys(const char *input, bool *output, const int output_size)
{
    unsigned int index = 0;
    int fd;
    unsigned int size = ((KEY_CNT) / 8);
    unsigned long keys[size];
    if (output_size < KEY_MAX)
    {
        return 2;
    }

    if ((fd = open(input, O_RDONLY)) < 0)
    {
        return 1;
    }

    memset(keys, 0, sizeof(keys));
    ioctl(fd, EVIOCGBIT(EV_KEY, KEY_MAX), keys);

    for (index = 0; index < KEY_MAX; index++)
    {
        output[index] = enabled_code(index, keys);
    }
    return 0;
}

int get_valid_relative_axis(const char *input, bool *output, const int output_size){
    unsigned int index = 0;
    int fd;
    unsigned int size = ((REL_CNT) / 8);
    unsigned long keys[size];

    if (output_size < REL_MAX) return 2;
    if ((fd = open(input, O_RDONLY)) < 0) return 1;

    memset(keys, 0, sizeof(keys));
    ioctl(fd, EVIOCGBIT(EV_REL, REL_MAX), keys);

    for (index = 0; index < REL_MAX; index++)
        output[index] = enabled_code(index, keys);

    return 0;
}

unsigned int get_event_type_max(const unsigned char event_type){

    switch (event_type)
    {
        case EV_SYN:
            return (unsigned int) SYN_MAX;
        case EV_KEY:
            return (unsigned int) KEY_MAX;
        case EV_REL:
            return (unsigned int) REL_MAX;
        case EV_ABS:
            return (unsigned int) ABS_MAX;
        case EV_MSC:
            return (unsigned int) MSC_MAX;
        case EV_SW:
            return (unsigned int) SW_MAX;
        case EV_LED:
            return (unsigned int) LED_MAX;
        case EV_SND:
            return (unsigned int) SND_MAX;
        case EV_REP:
            return (unsigned int) REP_MAX;
        case EV_FF:
            return (unsigned int) FF_MAX;
        case EV_FF_STATUS:
            return (unsigned int) FF_STATUS_MAX;
        // Note: EV_PWR doses not map to max;
        default:
            return 0;
    }
}

int get_valid(const char *input, bool *output, const int output_size, const unsigned char event_type){

    const unsigned int max = get_event_type_max(event_type);
    const unsigned int count = max + 1;

    unsigned int index = 0;
    int fd;
    unsigned int size = ((count) / 8);
    unsigned long keys[size];

    if (output_size < max) return 2;
    if ((fd = open(input, O_RDONLY)) < 0) return 1;

    memset(keys, 0, sizeof(keys));
    ioctl(fd, EVIOCGBIT(event_type, max), keys);

    for (index = 0; index < max; index++)
        output[index] = enabled_code(index, keys);

    return 0;
}
